on: ["push", "pull_request"]

name: Publish Package to npmjs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Publish
      run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

