name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Updation depencencies
      uses: Borales/actions-yarn@v2.3.0
      with: 
        cmd: install

    - name: Linting
      run: yarn lint:js

    - name: Testing
      run: yarn test

    - name: Build
      run: |
        npx webpack
